name:                matching
version:             0.1.0.0
github:              "kframework/llvm-backend"
license:             "UIUC"
author:              "Radu Ometita"
maintainer:          "radu.ometita@gmail.com"
copyright:           "2018 Runtime Verification, Inc."

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kframework/llvm-backend>

dependencies:
- base >= 4.7 && < 5
- recursion-schemes
- text
- text-show
- yaml
- bytestring
- kore
- containers

executables:
    matching:
        main: Main.hs
        source-dirs: src
        gcs-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - matching

library:
  source-dirs: src
  ghc-options:
    - -Wall

tests:
  matching-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:        
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - matching
    - tasty
    - tasty-hunit
